#!/bin/sh
set -euC

if [ "$#" -eq 0 ]; then
    (
        printf 'This will start the plutus-playground-server in the appropriate nix-shell.\n'
        printf 'Wait for the server to say “Interpreter ready”, then open a new terminal\n'
        printf 'and proceed with: %s --client\n\n' "$0"
        cd plutus-ea0ca4e9f
        nix-shell --run 'cd plutus-playground-client && plutus-playground-server'
    )
elif [ "$#" -eq 1 ] && [ "$1" = '--client' ]; then
    (
        cd plutus-ea0ca4e9f
        nix-shell --run 'cd plutus-playground-client && npm start'
    )
else
    printf 'I do not know what to do with the given arguments.\n'
    printf 'Usage: %s (no arguments)\n' "$0"
    printf '       %s --client\n' "$0"
    exit 7
fi
